packages:
  - 'packages/**'
  - '!**/test/**'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.57939439ddcb16d9f54ebf7d41432893182ee46d
  vitest: 4.1.10
  vite-plus: 0.0.0-commit.57939439ddcb16d9f54ebf7d41432893182ee46d
overrides:
  '@docsearch/js>preact': 10.29.0
  lodash: 4.17.23
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
