packages:
  - 'packages/**'
  - '!**/test/**'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89
  vitest: 4.1.10
  vite-plus: 0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89
overrides:
  '@docsearch/js>preact': 10.29.0
  lodash: 4.17.23
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
